server:
  port: 8000

spring:
  application:
    name: service-order
  profiles:
    active: dev
    include: feign

# rocketmq
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: order-producer-group
